name: "EsLinter"

on:
  push:
    branches: [main] 
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setting up Node Environment
        uses: actions/setup-node@v4.0.0

      - name: Installing dependencies
        run: npm install

      - name: Linting
        run: npm run lint
